### ISSUE TITLE
[REQUEST] Add the best practice rules to eslint config

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#10]
**Is your feature request related to a problem? Please describe.**

Currently there's a lot of loopholes to write bad code due to ESLint not linting them.

**Describe the solution you would like**

Add the best practice rules to eslint config.

**Comment by Twaha-Rahman** [comment]
@snowteamer I can use some help from as this is one of your expertise.....

**Comment by snowteamer** [comment]
As a first step, we could enable the recommended ESLint rules besides Prettier's.
