### ISSUE TITLE
[REQUEST] Add an error handler to the Mongoose sample injector

### ISSUE THREAD

**Issue by magnus195** [Twaha-Rahman/e-commercify#13]
**Is your feature request related to a problem? Please describe.**
I had some problems writing a decent error handler and got errors from it (not the good ones).

**Describe the solution you would like**
I never figured out how to make it work in a good way so I'm hoping someone can look at it if my PR get's merged.
This can be considered low priority

**Additional context**
This issue is related to #9

**Comment by Twaha-Rahman** [comment]
An error handler was added with #32.
