### ISSUE TITLE
[REQUEST] Make a bigger variety of fake products

### ISSUE THREAD

**Issue by magnus195** [Twaha-Rahman/e-commercify#14]
**Is your feature request related to a problem? Please describe.**
The products are getting repetitive. We need more of them.

**Describe the solution you would like**
If someone could either write or find a module that could randomly generate a new product each time, we'd have more interesting data to work with.

**Describe alternatives you have considered**
I have found some modules where you can generate fake person data. I don't know about product data though

**Comment by Twaha-Rahman** [comment]
I think it would be a nice thing to have, but not a high priority.
