### ISSUE TITLE
Refactor code to use Async/Await

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#45]
Currently the codebase some `.then()` and `.catch()` here and there. We need to replace **all** of these with `Async/Await` as it is much more cleaner.

An IIFE can be used in the `main.js` file to achieve this refactoring.

**Comment by snowteamer** [comment]
Persnally I like both patterns, I think each has valid use cases.

Regarding refactoring, should we also move the connection success/failure handlers to the `connectToMongo()` function?

**Comment by Twaha-Rahman** [comment]
> Persnally I like both patterns, I think each has valid use cases.
> 
> Regarding refactoring, should we also move the connection success/failure handlers to the `connectToMongo()` function?

I guess that makes perfect sense. Go for it.
