### ISSUE TITLE
[REQUEST] Agree on a fetch package

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#59]
**Is your feature request related to a problem? Please describe.**

We'll start writing tests for our completed endpoints and for that we'll need to send a request somehow. I know that Node.js has `HTTPS` as a standard library that can be used for this sort of stuff but it's quite low-level and doesn't support **HTTPS** by default. That's why I'm asking that we agree on a popular fetch package from NPM.

**Describe the solution you would like**

I'd like to suggest [node-fetch](https://www.npmjs.com/package/node-fetch) as a really competent library. If we use this library, we'll be able to use the almost identical API in the frontend too.

**Describe alternatives you have considered**

Use the`HTTPS` standard library provided with Node.js

**Comment by snowteamer** [comment]
I have used the ´request` library in the past but it is no longer recommended, so I will agree on node-fetch.
