### ISSUE TITLE
[BUG] Injection script doesn't take note of flags passed

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#66]
**Describe the bug**

The sample data injection script currently doesn't take note of the flags passed.

***To Reproduce***
How can we reproduce this bug?
1. Run `npm run fill-db -k`
2. Observe the issue

**Expected behavior**

The sample data injection script should take note of the flags passed.

**Screenshots**

![Screenshot (2)](https://user-images.githubusercontent.com/39026437/86515810-8ca30d80-be3d-11ea-8baf-14df68fadc6a.png)

**Comment by nhcarrigan** [comment]
So I did a little digging. 
If you're calling the script via the `npm run` command, you have to separate the script name from the args. 
`npm run fill-db -k` won't pass any arguments to the script. `npm run fill-db -- -k` will pass the `-k` argument to the script. 

I tested this with both `npm run fill-db -- -k` and `npm run fill-db -- --keep` and both behaved as intended.

**Comment by Twaha-Rahman** [comment]
> So I did a little digging.
> If you're calling the script via the `npm run` command, you have to separate the script name from the args.
> `npm run fill-db -k` won't pass any arguments to the script. `npm run fill-db -- -k` will pass the `-k` argument to the script.
> 
> I tested this with both `npm run fill-db -- -k` and `npm run fill-db -- --keep` and both behaved as intended.

Ahhh... I see. Closing this issue then.
