### ISSUE TITLE
Make all the mutation endpoints XSS proof

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#84]
We'd need to update the mutation endpoints to be XSS proof. We'll use [Helmet.js](https://www.npmjs.com/package/helmet) for this job as it is a well established library for the job.

**Comment by snowteamer** [comment]
Is there something else we can do to further secure the mutation endpoints?

**Comment by Twaha-Rahman** [comment]
We'll have to test the endpoints with a XSS attack before we can close this issue.
