### ISSUE TITLE
✨[Feature] Add JSDoc for all JS files

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#85]
**Is your feature request related to a problem? Please describe.**

JSDoc is a markup language used to annotate JavaScript source code files. It has become a standard for code documentation and used widely in the industry.

**Describe the solution you would like**

Add JSDoc at the beginning of each file.

You may use this site as a doc for JSDoc -> 

https://jsdoc.app/about-getting-started.html

**Comment by snowteamer** [comment]
This should be easy if we use it only as file overviews.

**Comment by Twaha-Rahman** [comment]
We'll also add JSDOc for all `module` functions. Any function that is not a `module` should be excluded. A sample JSDoc for a `module` will look like -

```js
/**
 * Assign the project to an employee.
 * @param {Object} employee - The employee who is responsible for the project.
 * @param {string} employee.name - The name of the employee.
 * @param {string} employee.department - The employee's department.
 * @param {number} priority - A positive number representing the priority
 */
function assign(employee, priority) {
    // ...
};
```
