### ISSUE TITLE
✨[Feature] Add a `log` module for logging info (console + DB)

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#86]
**Is your feature request related to a problem? Please describe.**

Currently we log output to the console using `console.log()` directly. For this common functionality the same code in written repeatedly. We should have a `log` module that we'll can use for a centralized logging tool. This'll help with -

- [x] Checking if it is production or development and logging according to it
- [x] Log stuff to the DB when necessary
- [x] Formatting the logged message according to different priority
- [x] Easier debugging and modularity

**Describe the solution you would like**

Create a `log` module.

**Additional context**

I've used _log_ as the module name here but it isn't set and stone. We could call this module a different name.

**Comment by snowteamer** [comment]
There is likely already a mature logging package somewhere on NPM

**Comment by Twaha-Rahman** [comment]
> There is likely already a mature logging package somewhere on NPM

@snowteamer I haven't looked for any NPM package tbh. Can you suggest any?

**Comment by snowteamer** [comment]
Unfortunately I am not familiar with any :(
