### ISSUE TITLE
✨[Feature] Agree on a file naming scheme

### ISSUE THREAD

**Issue by Twaha-Rahman** [Twaha-Rahman/e-commercify#91]
**Is your feature request related to a problem? Please describe.**

Currently we are naming our files using both `camelCase` and `kebab-case`.

**Describe the solution you would like**

 We need to agree on one naming convention and stick to it.

**Additional context**

We'll rename the files when we have finished the MVP API on the backend and moved towards the frontend. This'll be done as to minimize merge conflicts.

**Comment by snowteamer** [comment]
I think upper CamelCase for constructors and lower camelCase for functions would be fine. However kebab-case is recommended for NPM packages, so if we wanted to refactor some modules into independent packages they would have to be renamed in kebab-case.
